server:
  port: 8084
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      min-spare: 5
      max: 50
spring:
  application:
    name: liquibase-integation
  datasource:
    username: dear
    password: comrade
    url: jdbc:postgresql://localhost:5432/dear_comrade
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  liquibase:
    change-log: "classpath:database/migration/topic-type-migration.yaml"
#    change-log: "classpath:database/migration/database-migration-change-log.yaml"
logging:
  level:
    "liquibase" : info