spring:
  application:
    name: migration-flyway
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/dha
  flyway:
    url: jdbc:postgresql://localhost:5432/dha
    user: root
    password: root

