version: "3.9"
services:
  oracle-std-service:
    shm_size: '8gb'
    container_name: oracle-std-service-container
    ports:
      - '9445:1521'
    image: container-registry.oracle.com/database/standard
    environment:
      DB_SID: OraDoc
      DB_PASSWD: MyPasswd123
      DB_DOMAIN: my.domain.com
      DB_BUNDLE: basic
